# Makefile automatically generated by ghdl
# Version: GHDL 4.1.0 (4.1.0.r0.g7188e92cf) [Dunoon edition] - llvm 14.0.0 code generator
# Command used to generate this makefile:
# ghdl --gen-makefile --ieee=synopsys -fexplicit UdpEngineTb

GHDLDIR ?= /usr/local/lib/ghdl
GHDL=ghdl
GHDLFLAGS= --ieee=synopsys -fexplicit
GHDLRUNFLAGS= --vpi=$$(cocotb-config --lib-name-path vpi ghdl) --wave=$(WAVEFILENAME).ghw
WAVEFILENAME := wave

# Default target
all: udpenginetb

# Elaboration target
udpenginetb: $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_1164-body.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/numeric_std.o $(GHDLDIR)/ieee/v93/numeric_std-body.o $(GHDLDIR)/ieee/v93/math_real.o $(GHDLDIR)/ieee/v93/math_real-body.o StdRtlPkg.o AxiStreamPkg.o SsiPkg.o EthMacPkg.o $(GHDLDIR)/std/v93/textio.o $(GHDLDIR)/std/v93/textio-body.o TextUtilPkg.o AxiLitePkg.o AxiStreamPipeline.o AxiStreamResize.o AxiStreamGearbox.o FifoXpmDummy.o FifoAlteraMfDummy.o Synchronizer.o RstSync.o SynchronizerVector.o FifoWrFsm.o FifoRdFsm.o SimpleDualPortRam.o FifoOutputPipeline.o FifoAsync.o FifoSync.o Fifo.o FifoCascade.o AxiStreamFifoV2.o SsiPrbsTx.o IpV4EngineDeMux.o ArbiterPkg.o AxiStreamMux.o ArpEngine.o AxiStreamDeMux.o IpV4EngineRx.o IpV4EngineTx.o IcmpEngine.o IgmpV2Engine.o IpV4Engine.o UdpEngineRx.o UdpEngineDhcp.o UdpEngineTx.o Arbiter.o ArpIpTable.o UdpEngineArp.o UdpEngine.o UdpEngineWrapper.o EthMacTxFifo.o EthMacTxBypass.o EthMacTxCsum.o EthMacTxPause.o EthMacTxExportXlgmii.o CrcPkg.o Crc32Parallel.o EthMacTxExportXgmii.o EthMacTxExportGmii.o EthMacTxExport.o EthMacTx.o EthMacFlowCtrl.o EthMacRxImportXlgmii.o EthMacRxImportXgmii.o EthMacRxImportGmii.o EthMacRxImport.o EthMacRxPause.o EthMacRxCsum.o EthMacRxBypass.o EthMacRxFilter.o EthMacRx.o SsiIbFrameFilter.o SsiObFrameFilter.o SsiFifo.o EthMacRxFifo.o EthMacTop.o UdpEngineTb.o
	$(GHDL) -e $(GHDLFLAGS) $@

# Run target
run: udpenginetb
	$(GHDL) -r udpenginetb $(GHDLRUNFLAGS)

# Targets to analyze files
$(GHDLDIR)/ieee/v93/std_logic_1164.o: $(GHDLDIR)/ieee/v93/../../src/ieee/v93/std_logic_1164.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
$(GHDLDIR)/ieee/v93/std_logic_1164-body.o: $(GHDLDIR)/ieee/v93/../../src/ieee/v93/std_logic_1164-body.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
$(GHDLDIR)/ieee/v93/std_logic_arith.o: $(GHDLDIR)/ieee/v93/../../src/synopsys/std_logic_arith.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
$(GHDLDIR)/ieee/v93/std_logic_unsigned.o: $(GHDLDIR)/ieee/v93/../../src/synopsys/std_logic_unsigned.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
$(GHDLDIR)/ieee/v93/numeric_std.o: $(GHDLDIR)/ieee/v93/../../src/ieee/v93/numeric_std.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
$(GHDLDIR)/ieee/v93/numeric_std-body.o: $(GHDLDIR)/ieee/v93/../../src/ieee/v93/numeric_std-body.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
$(GHDLDIR)/ieee/v93/math_real.o: $(GHDLDIR)/ieee/v93/../../src/ieee/math_real.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
$(GHDLDIR)/ieee/v93/math_real-body.o: $(GHDLDIR)/ieee/v93/../../src/ieee/math_real-body.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
StdRtlPkg.o: ../surf/base/general/rtl/StdRtlPkg.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
AxiStreamPkg.o: ../surf/axi/axi-stream/rtl/AxiStreamPkg.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
SsiPkg.o: ../surf/protocols/ssi/rtl/SsiPkg.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacPkg.o: ../surf/ethernet/EthMacCore/rtl/EthMacPkg.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
$(GHDLDIR)/std/v93/textio.o: $(GHDLDIR)/std/v93/../../src/std/v93/textio.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
$(GHDLDIR)/std/v93/textio-body.o: $(GHDLDIR)/std/v93/../../src/std/v93/textio-body.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
TextUtilPkg.o: ../surf/base/general/rtl/TextUtilPkg.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
AxiLitePkg.o: ../surf/axi/axi-lite/rtl/AxiLitePkg.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
AxiStreamPipeline.o: ../surf/axi/axi-stream/rtl/AxiStreamPipeline.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
AxiStreamResize.o: ../surf/axi/axi-stream/rtl/AxiStreamResize.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
AxiStreamGearbox.o: ../surf/axi/axi-stream/rtl/AxiStreamGearbox.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
FifoXpmDummy.o: ../surf/base/fifo/rtl/dummy/FifoXpmDummy.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
FifoAlteraMfDummy.o: ../surf/base/fifo/rtl/dummy/FifoAlteraMfDummy.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
Synchronizer.o: ../surf/base/sync/rtl/Synchronizer.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
RstSync.o: ../surf/base/sync/rtl/RstSync.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
SynchronizerVector.o: ../surf/base/sync/rtl/SynchronizerVector.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
FifoWrFsm.o: ../surf/base/fifo/rtl/inferred/FifoWrFsm.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
FifoRdFsm.o: ../surf/base/fifo/rtl/inferred/FifoRdFsm.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
SimpleDualPortRam.o: ../surf/base/ram/inferred/SimpleDualPortRam.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
FifoOutputPipeline.o: ../surf/base/fifo/rtl/FifoOutputPipeline.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
FifoAsync.o: ../surf/base/fifo/rtl/inferred/FifoAsync.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
FifoSync.o: ../surf/base/fifo/rtl/inferred/FifoSync.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
Fifo.o: ../surf/base/fifo/rtl/Fifo.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
FifoCascade.o: ../surf/base/fifo/rtl/FifoCascade.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
AxiStreamFifoV2.o: ../surf/axi/axi-stream/rtl/AxiStreamFifoV2.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
SsiPrbsTx.o: ../surf/protocols/ssi/rtl/SsiPrbsTx.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
IpV4EngineDeMux.o: ../surf/ethernet/IpV4Engine/rtl/IpV4EngineDeMux.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
ArbiterPkg.o: ../surf/base/general/rtl/ArbiterPkg.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
AxiStreamMux.o: ../surf/axi/axi-stream/rtl/AxiStreamMux.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
ArpEngine.o: ../surf/ethernet/IpV4Engine/rtl/ArpEngine.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
AxiStreamDeMux.o: ../surf/axi/axi-stream/rtl/AxiStreamDeMux.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
IpV4EngineRx.o: ../surf/ethernet/IpV4Engine/rtl/IpV4EngineRx.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
IpV4EngineTx.o: ../surf/ethernet/IpV4Engine/rtl/IpV4EngineTx.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
IcmpEngine.o: ../surf/ethernet/IpV4Engine/rtl/IcmpEngine.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
IgmpV2Engine.o: ../surf/ethernet/IpV4Engine/rtl/IgmpV2Engine.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
IpV4Engine.o: ../surf/ethernet/IpV4Engine/rtl/IpV4Engine.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
UdpEngineRx.o: ../surf/ethernet/UdpEngine/rtl/UdpEngineRx.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
UdpEngineDhcp.o: ../surf/ethernet/UdpEngine/rtl/UdpEngineDhcp.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
UdpEngineTx.o: ../surf/ethernet/UdpEngine/rtl/UdpEngineTx.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
Arbiter.o: ../surf/base/general/rtl/Arbiter.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
ArpIpTable.o: ../surf/ethernet/UdpEngine/rtl/ArpIpTable.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
UdpEngineArp.o: ../surf/ethernet/UdpEngine/rtl/UdpEngineArp.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
UdpEngine.o: ../surf/ethernet/UdpEngine/rtl/UdpEngine.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
UdpEngineWrapper.o: ../surf/ethernet/UdpEngine/rtl/UdpEngineWrapper.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacTxFifo.o: ../surf/ethernet/EthMacCore/rtl/EthMacTxFifo.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacTxBypass.o: ../surf/ethernet/EthMacCore/rtl/EthMacTxBypass.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacTxCsum.o: ../surf/ethernet/EthMacCore/rtl/EthMacTxCsum.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacTxPause.o: ../surf/ethernet/EthMacCore/rtl/EthMacTxPause.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacTxExportXlgmii.o: ../surf/ethernet/EthMacCore/rtl/EthMacTxExportXlgmii.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
CrcPkg.o: ../surf/base/crc/rtl/CrcPkg.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
Crc32Parallel.o: ../surf/base/crc/rtl/Crc32Parallel.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacTxExportXgmii.o: ../surf/ethernet/EthMacCore/rtl/EthMacTxExportXgmii.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacTxExportGmii.o: ../surf/ethernet/EthMacCore/rtl/EthMacTxExportGmii.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacTxExport.o: ../surf/ethernet/EthMacCore/rtl/EthMacTxExport.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacTx.o: ../surf/ethernet/EthMacCore/rtl/EthMacTx.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacFlowCtrl.o: ../surf/ethernet/EthMacCore/rtl/EthMacFlowCtrl.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacRxImportXlgmii.o: ../surf/ethernet/EthMacCore/rtl/EthMacRxImportXlgmii.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacRxImportXgmii.o: ../surf/ethernet/EthMacCore/rtl/EthMacRxImportXgmii.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacRxImportGmii.o: ../surf/ethernet/EthMacCore/rtl/EthMacRxImportGmii.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacRxImport.o: ../surf/ethernet/EthMacCore/rtl/EthMacRxImport.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacRxPause.o: ../surf/ethernet/EthMacCore/rtl/EthMacRxPause.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacRxCsum.o: ../surf/ethernet/EthMacCore/rtl/EthMacRxCsum.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacRxBypass.o: ../surf/ethernet/EthMacCore/rtl/EthMacRxBypass.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacRxFilter.o: ../surf/ethernet/EthMacCore/rtl/EthMacRxFilter.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacRx.o: ../surf/ethernet/EthMacCore/rtl/EthMacRx.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
SsiIbFrameFilter.o: ../surf/protocols/ssi/rtl/SsiIbFrameFilter.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
SsiObFrameFilter.o: ../surf/protocols/ssi/rtl/SsiObFrameFilter.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
SsiFifo.o: ../surf/protocols/ssi/rtl/SsiFifo.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacRxFifo.o: ../surf/ethernet/EthMacCore/rtl/EthMacRxFifo.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
EthMacTop.o: ../surf/ethernet/EthMacCore/rtl/EthMacTop.vhd
	$(GHDL) -a $(GHDLFLAGS) --work=surf --workdir=. $<
UdpEngineTb.o: ../cocotb-test/rtl/UdpEngineTb.vhd
	$(GHDL) -a $(GHDLFLAGS) $<

# Files dependences
$(GHDLDIR)/ieee/v93/std_logic_1164.o: 
$(GHDLDIR)/ieee/v93/std_logic_1164-body.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o
$(GHDLDIR)/ieee/v93/std_logic_arith.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o
$(GHDLDIR)/ieee/v93/std_logic_unsigned.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o
$(GHDLDIR)/ieee/v93/numeric_std.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o
$(GHDLDIR)/ieee/v93/numeric_std-body.o:  $(GHDLDIR)/ieee/v93/numeric_std.o
$(GHDLDIR)/ieee/v93/math_real.o: 
$(GHDLDIR)/ieee/v93/math_real-body.o:  $(GHDLDIR)/ieee/v93/math_real.o
StdRtlPkg.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/numeric_std.o $(GHDLDIR)/ieee/v93/math_real.o
AxiStreamPkg.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o
SsiPkg.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiStreamPkg.o
EthMacPkg.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiStreamPkg.o
$(GHDLDIR)/std/v93/textio.o: 
$(GHDLDIR)/std/v93/textio-body.o:  $(GHDLDIR)/std/v93/textio.o
TextUtilPkg.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/std/v93/textio.o StdRtlPkg.o
AxiLitePkg.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/numeric_std.o StdRtlPkg.o TextUtilPkg.o
AxiStreamPipeline.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o StdRtlPkg.o AxiStreamPkg.o
AxiStreamResize.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiStreamPkg.o AxiStreamPipeline.o
AxiStreamGearbox.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiStreamPkg.o AxiStreamResize.o AxiStreamPipeline.o
FifoXpmDummy.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o
FifoAlteraMfDummy.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o
Synchronizer.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o StdRtlPkg.o
RstSync.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o StdRtlPkg.o Synchronizer.o
SynchronizerVector.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o StdRtlPkg.o
FifoWrFsm.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o
FifoRdFsm.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o
SimpleDualPortRam.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o
FifoOutputPipeline.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o StdRtlPkg.o
FifoAsync.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o RstSync.o SynchronizerVector.o Synchronizer.o FifoWrFsm.o FifoRdFsm.o SimpleDualPortRam.o FifoOutputPipeline.o
FifoSync.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o FifoWrFsm.o FifoRdFsm.o SimpleDualPortRam.o FifoOutputPipeline.o
Fifo.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/numeric_std.o StdRtlPkg.o FifoXpmDummy.o FifoAlteraMfDummy.o FifoAsync.o FifoSync.o
FifoCascade.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/numeric_std.o StdRtlPkg.o Fifo.o
AxiStreamFifoV2.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiStreamPkg.o AxiStreamGearbox.o FifoCascade.o Synchronizer.o AxiStreamPipeline.o
SsiPrbsTx.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiLitePkg.o AxiStreamPkg.o SsiPkg.o AxiStreamFifoV2.o
IpV4EngineDeMux.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiStreamPkg.o SsiPkg.o EthMacPkg.o
ArbiterPkg.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/numeric_std.o StdRtlPkg.o
AxiStreamMux.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o ArbiterPkg.o AxiStreamPkg.o AxiStreamPipeline.o
ArpEngine.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiStreamPkg.o SsiPkg.o EthMacPkg.o
AxiStreamDeMux.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/numeric_std.o StdRtlPkg.o ArbiterPkg.o AxiStreamPkg.o AxiStreamPipeline.o
IpV4EngineRx.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiStreamPkg.o SsiPkg.o EthMacPkg.o AxiStreamMux.o AxiStreamDeMux.o
IpV4EngineTx.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiStreamPkg.o SsiPkg.o EthMacPkg.o AxiStreamMux.o AxiStreamPipeline.o AxiStreamDeMux.o
IcmpEngine.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiStreamPkg.o SsiPkg.o EthMacPkg.o
IgmpV2Engine.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiStreamPkg.o SsiPkg.o EthMacPkg.o
IpV4Engine.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o StdRtlPkg.o AxiStreamPkg.o EthMacPkg.o IpV4EngineDeMux.o AxiStreamMux.o ArpEngine.o IpV4EngineRx.o IpV4EngineTx.o IcmpEngine.o IgmpV2Engine.o
UdpEngineRx.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiStreamPkg.o SsiPkg.o EthMacPkg.o AxiStreamPipeline.o AxiStreamDeMux.o
UdpEngineDhcp.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiStreamPkg.o SsiPkg.o EthMacPkg.o AxiStreamFifoV2.o
UdpEngineTx.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiStreamPkg.o SsiPkg.o EthMacPkg.o AxiStreamPipeline.o
Arbiter.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o ArbiterPkg.o
ArpIpTable.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o Arbiter.o Fifo.o
UdpEngineArp.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiStreamPkg.o
UdpEngine.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o StdRtlPkg.o AxiStreamPkg.o UdpEngineRx.o UdpEngineDhcp.o UdpEngineTx.o ArpIpTable.o UdpEngineArp.o AxiStreamMux.o
UdpEngineWrapper.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiLitePkg.o AxiStreamPkg.o EthMacPkg.o IpV4Engine.o UdpEngine.o
EthMacTxFifo.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o StdRtlPkg.o AxiStreamPkg.o EthMacPkg.o AxiStreamFifoV2.o
EthMacTxBypass.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o AxiStreamPkg.o StdRtlPkg.o EthMacPkg.o
EthMacTxCsum.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o AxiStreamPkg.o EthMacPkg.o AxiStreamPipeline.o AxiStreamFifoV2.o Fifo.o
EthMacTxPause.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o AxiStreamPkg.o StdRtlPkg.o EthMacPkg.o
EthMacTxExportXlgmii.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o AxiStreamPkg.o StdRtlPkg.o EthMacPkg.o
CrcPkg.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o StdRtlPkg.o
Crc32Parallel.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o CrcPkg.o
EthMacTxExportXgmii.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o AxiStreamPkg.o StdRtlPkg.o EthMacPkg.o AxiStreamFifoV2.o Fifo.o Crc32Parallel.o
EthMacTxExportGmii.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o AxiStreamPkg.o EthMacPkg.o AxiStreamResize.o Crc32Parallel.o
EthMacTxExport.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o AxiStreamPkg.o StdRtlPkg.o EthMacTxExportXlgmii.o EthMacTxExportXgmii.o EthMacTxExportGmii.o
EthMacTx.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o AxiStreamPkg.o StdRtlPkg.o EthMacPkg.o EthMacTxBypass.o EthMacTxCsum.o EthMacTxPause.o EthMacTxExport.o
EthMacFlowCtrl.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o AxiStreamPkg.o
EthMacRxImportXlgmii.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o AxiStreamPkg.o StdRtlPkg.o EthMacPkg.o
EthMacRxImportXgmii.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o AxiStreamPkg.o StdRtlPkg.o EthMacPkg.o AxiStreamResize.o Fifo.o Crc32Parallel.o
EthMacRxImportGmii.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o AxiStreamPkg.o EthMacPkg.o AxiStreamFifoV2.o Crc32Parallel.o
EthMacRxImport.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o AxiStreamPkg.o StdRtlPkg.o EthMacPkg.o EthMacRxImportXlgmii.o EthMacRxImportXgmii.o EthMacRxImportGmii.o
EthMacRxPause.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o AxiStreamPkg.o StdRtlPkg.o EthMacPkg.o
EthMacRxCsum.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o AxiStreamPkg.o EthMacPkg.o
EthMacRxBypass.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o AxiStreamPkg.o StdRtlPkg.o EthMacPkg.o
EthMacRxFilter.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o AxiStreamPkg.o StdRtlPkg.o EthMacPkg.o
EthMacRx.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o AxiStreamPkg.o StdRtlPkg.o EthMacPkg.o EthMacRxImport.o EthMacRxPause.o EthMacRxCsum.o EthMacRxBypass.o EthMacRxFilter.o
SsiIbFrameFilter.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o AxiStreamPkg.o SsiPkg.o
SsiObFrameFilter.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o AxiStreamPkg.o SsiPkg.o AxiStreamPipeline.o
SsiFifo.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o AxiStreamPkg.o SsiPkg.o SsiIbFrameFilter.o AxiStreamFifoV2.o SsiObFrameFilter.o AxiStreamGearbox.o
EthMacRxFifo.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o $(GHDLDIR)/ieee/v93/std_logic_arith.o StdRtlPkg.o AxiStreamPkg.o EthMacPkg.o SsiFifo.o
EthMacTop.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o AxiStreamPkg.o StdRtlPkg.o EthMacPkg.o EthMacTxFifo.o EthMacTx.o EthMacFlowCtrl.o EthMacRx.o EthMacRxFifo.o
UdpEngineTb.o:  $(GHDLDIR)/ieee/v93/std_logic_1164.o $(GHDLDIR)/ieee/v93/std_logic_arith.o $(GHDLDIR)/ieee/v93/std_logic_unsigned.o StdRtlPkg.o AxiStreamPkg.o SsiPkg.o EthMacPkg.o AxiLitePkg.o SsiPrbsTx.o UdpEngineWrapper.o EthMacTop.o

clean:
	rm *.o *.cf *.ghw *.xml udpenginetb
